force-app/main/default/objects/Exchange_Rate_API_Config__mdt/Exchange_Rate_API_Config__mdt.object-meta.xml
<CustomObject>
    <label>Exchange Rate API Config</label>
    <pluralLabel>Exchange Rate API Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate_API_Config__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Name of Apex Class to call from Schedulable for Exchange Rate API</description>
    <label>Apex Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate_API_Config__mdt/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate_API_Config__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Key from Exchange Rate API</description>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate_API_Config__mdt/fields/Base_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Currency__c</fullName>
    <description>Base Currency Code ex. USD</description>
    <label>Base Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExchangeRateScheduler.cls
/**
 * @description Scheduler class to run the exchange rate update on a schedule
 * Scheduling should be done in Salesforce Setup Apex Classes -> Schedule Apex
 */
global class ExchangeRateScheduler implements Schedulable {
    
    @TestVisible
    private Exchange_Rate_API_Config__mdt config; 

    @TestVisible
    private Callable classInstance;

    /**
     * @description Executes the scheduled job to update exchange rates
     * @param context The SchedulableContext
     */
    global void execute(SchedulableContext sc) {
        // 1. Call ExchangeRateService.updateExchangeRates()
        // 2. Add error handling
        // 3. Consider adding logging if available
        try {
            if(config == null) {
                config = [SELECT Id, API_Key__c, Base_Currency__c, Apex_Class_Name__c FROM Exchange_Rate_API_Config__mdt LIMIT 1];
            }
            Map<String, Object> params = new Map<String, Object>{
                'config' => config
            };
            classInstance = (Callable) Type.forName(config.Apex_Class_Name__c).newInstance();
            Object obj = classInstance.call(config.Apex_Method__c, params);
            //ExchangeRateService.updateExchangeRates();
        } catch (Exception e) {
            System.debug('Error with Exchange Rate job: ' + e.getMessage());
        }
        
    }
}